---
- hosts: localhost
  connection: local
  become: yes
  remote_user: ansible
  vars_files: 
  - vars.yaml
  roles:
   # - { role: 'secrets' }
  - { role: 'secrets' , pending_password: "{{abc.results[9].stdout | trim}}" , position_password: "{{abc.results[12].stdout | trim}}" , portfolio_password: "{{abc.results[10].stdout | trim}}" }
  pre_tasks:   
  - name: fetch password from pmp
    script: test.py {{ item }}
    args:
      executable: python
    with_items: "{{ accountid }}"
    register: abc

#  - debug:
#      var: abc.results[15]

