---
- hosts: localhost
  become: yes
  remote_user: rajeev
  vars_files: 
  - vars.yaml
  roles:
          #- { role: 'secrets' }
  - { role: 'secrets' , pending_password: "{{abc.results[1].stdout | trim}}" }
  pre_tasks:   
  - name: fetch password from pmp
    script: test.py {{ item }}
    args:
      executable: python
    with_items: "{{ accountid }}"
    register: abc

  - debug:
      var: abc.results[1].stdout | trim

  - copy:
      content: "{{ abc.results[1].stdout | trim }}"
      dest: /tmp/pmp
