---
- hosts: localhost
  become: yes
  remote_user: rajeev
  vars_files: 
  - vars.yaml
  roles:
  - { role: 'secrets'  }
  tasks:
   
  - name: fetch password from pmp
    script: /root/rajeev/pmp-ansible/test.py {{ account_id  }}
    args:
      executable: python
    loop:
      - "307"
      - "301"
    register: abc
  - debug:
      var: abc
  - debug:
      msg: "{{ abc.results[1].stdout | trim }}"
