---
# tasks file for secrets
- name: create secrets in kubernetes
  shell: |-
    cat /root/rajeev/pmpansible/secrets/files/values.yaml
- name: copy the files
  template:
    src: "../files/values.yaml"
    dest: /tmp/values.yaml
